/********************************************************************
* dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledict();
extern void G__cpp_setup_inheritancedict();
extern void G__cpp_setup_typetabledict();
extern void G__cpp_setup_memvardict();
extern void G__cpp_setup_globaldict();
extern void G__cpp_setup_memfuncdict();
extern void G__cpp_setup_funcdict();
extern void G__set_cpp_environmentdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MainGui.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictLN_string;
extern G__linked_taginfo G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__dictLN_TGMainFrame;
extern G__linked_taginfo G__dictLN_TGRadioButton;
extern G__linked_taginfo G__dictLN_TGNumberEntry;
extern G__linked_taginfo G__dictLN_TGComboBox;
extern G__linked_taginfo G__dictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_TCanvas;
extern G__linked_taginfo G__dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__dictLN_ProcessPosition;
extern G__linked_taginfo G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlEScanDefcOallocatorlEScanDefgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEScanDefcOallocatorlEScanDefgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlEProcessPositioncOallocatorlEProcessPositiongRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEProcessPositioncOallocatorlEProcessPositiongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_HistoReader;
extern G__linked_taginfo G__dictLN_vectorlETH2CmUcOallocatorlETH2CmUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETH2CmUcOallocatorlETH2CmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_MainGui;
extern G__linked_taginfo G__dictLN_vectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
