//
// File generated by rootcint at Mon Mar 30 19:29:17 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void MainGui_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void MainGui_Dictionary();
   static void *new_MainGui(void *p = 0);
   static void *newArray_MainGui(Long_t size, void *p);
   static void delete_MainGui(void *p);
   static void deleteArray_MainGui(void *p);
   static void destruct_MainGui(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::MainGui*)
   {
      ::MainGui *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::MainGui),0);
      static ::ROOT::TGenericClassInfo 
         instance("MainGui", "./MainGui.hh", 136,
                  typeid(::MainGui), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &MainGui_Dictionary, isa_proxy, 0,
                  sizeof(::MainGui) );
      instance.SetNew(&new_MainGui);
      instance.SetNewArray(&newArray_MainGui);
      instance.SetDelete(&delete_MainGui);
      instance.SetDeleteArray(&deleteArray_MainGui);
      instance.SetDestructor(&destruct_MainGui);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::MainGui*)
   {
      return GenerateInitInstanceLocal((::MainGui*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MainGui*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void MainGui_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::MainGui*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_MainGui(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MainGui : new ::MainGui;
   }
   static void *newArray_MainGui(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MainGui[nElements] : new ::MainGui[nElements];
   }
   // Wrapper around operator delete
   static void delete_MainGui(void *p) {
      delete ((::MainGui*)p);
   }
   static void deleteArray_MainGui(void *p) {
      delete [] ((::MainGui*)p);
   }
   static void destruct_MainGui(void *p) {
      typedef ::MainGui current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::MainGui

/********************************************************
* dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledict();

extern "C" void G__set_cpp_environmentdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("MainGui.hh");
  G__cpp_reset_tagtabledict();
}
#include <new>
extern "C" int G__cpp_dllrevdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MainGui */
static int G__dict_613_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MainGui* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MainGui[n];
     } else {
       p = new((void*) gvp) MainGui[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MainGui;
     } else {
       p = new((void*) gvp) MainGui;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_MainGui));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_613_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainGui*) G__getstructoffset())->PrintCanvas();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_613_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainGui*) G__getstructoffset())->DoModuleLoad();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_613_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainGui*) G__getstructoffset())->DoStaveLoad();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_613_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainGui*) G__getstructoffset())->DoMainFrameClose();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_613_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainGui*) G__getstructoffset())->DoModuleSelected((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_613_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainGui*) G__getstructoffset())->DoStaveModuleSelected((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_613_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainGui*) G__getstructoffset())->DoStaveSelected((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_613_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   MainGui* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new MainGui(*(MainGui*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_MainGui));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MainGui G__TMainGui;
static int G__dict_613_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MainGui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MainGui*) (soff+(sizeof(MainGui)*i)))->~G__TMainGui();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MainGui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MainGui*) (soff))->~G__TMainGui();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_613_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MainGui* dest = (MainGui*) G__getstructoffset();
   *dest = *(MainGui*) libp->para[0].ref;
   const MainGui& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MainGui */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict {
 public:
  G__Sizep2memfuncdict(): p(&G__Sizep2memfuncdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict::*p)();
};

size_t G__get_sizep2memfuncdict()
{
  G__Sizep2memfuncdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__dictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__dictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ScanDef>",117,G__get_linked_tagnum(&G__dictLN_vectorlEScanDefcOallocatorlEScanDefgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEScanDefcOallocatorlEScanDefgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEScanDefcOallocatorlEScanDefgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEScanDefcOallocatorlEScanDefgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEScanDefcOallocatorlEScanDefgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ProcessPosition>",117,G__get_linked_tagnum(&G__dictLN_vectorlEProcessPositioncOallocatorlEProcessPositiongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEProcessPositioncOallocatorlEProcessPositiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEProcessPositioncOallocatorlEProcessPositiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEProcessPositioncOallocatorlEProcessPositiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEProcessPositioncOallocatorlEProcessPositiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2C*>",117,G__get_linked_tagnum(&G__dictLN_vectorlETH2CmUcOallocatorlETH2CmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETH2CmUcOallocatorlETH2CmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETH2CmUcOallocatorlETH2CmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETH2CmUcOallocatorlETH2CmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETH2CmUcOallocatorlETH2CmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<IVMeasurementPoint>",117,G__get_linked_tagnum(&G__dictLN_vectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<HistoReader*>",117,G__get_linked_tagnum(&G__dictLN_vectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGraph*>",117,G__get_linked_tagnum(&G__dictLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGCheckButton*>",117,G__get_linked_tagnum(&G__dictLN_vectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MainGui */
static void G__setup_memvarMainGui(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictLN_MainGui));
   { MainGui *p; p=(MainGui*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->modules)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,1,"modules=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->modules_loaded)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,1,"modules_loaded=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->modules_complete)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,1,"modules_complete=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGMainFrame),-1,-1,2,"mainFrame=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,2,"stave_modules=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,2,"stave_modules_posid=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGComboBox),-1,-1,2,"moduleComboBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGComboBox),-1,-1,2,"moduleComboBox2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGComboBox),-1,-1,2,"stave_moduleComboBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_processpoint_usbpix=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_processpoint_rce=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_processpoint_usbpix_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_processpoint_rce_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_processpoint_usbpix_2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_processpoint_rce_2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_chip_0=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_chip_1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_chip_0_B=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_module_chip_1_B=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_stave_processpoint_afterTC_BT=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_stave_processpoint_beforeTC_BT=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_stave_processpoint_RT=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_stave_processpoint_afterTC_AT=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_stave_processpoint_beforeTC_AT=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_stave_compRT=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_stave_compAll=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dictLN_vectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgR),G__defined_typename("vector<TGCheckButton*>"),-1,2,"module_analysis_checkbuttons=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dictLN_vectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgR),G__defined_typename("vector<TGCheckButton*>"),-1,2,"stave_analysis_checkbuttons=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_hvon=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_hvoff=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_hvon_B=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_hvoff_B=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_hvon_th=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGRadioButton),-1,-1,2,"radiobutton_hvoff_th=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TGNumberEntry),-1,-1,2,"fNumberEntry747=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_HistoReader),-1,-1,2,"moduleHistoReader=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,2,"staves=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,2,"module_histograms=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TCanvas),-1,-1,2,"module_canvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TCanvas),-1,-1,2,"module_canvas_s=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"m_enable_stave_module_comparison=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"m_stave_module_id=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMainGui(void) {
   /* MainGui */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictLN_MainGui));
   G__memfunc_setup("MainGui",682,G__dict_613_0_1, 105, G__get_linked_tagnum(&G__dictLN_MainGui), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintCanvas",1129,G__dict_613_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoModuleLoad",1177,G__dict_613_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoStaveLoad",1078,G__dict_613_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoMainFrameClose",1561,G__dict_613_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoModuleSelected",1602,G__dict_613_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoStaveModuleSelected",2117,G__dict_613_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoStaveSelected",1503,G__dict_613_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadModuleList",1410,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadStaveModuleList",1925,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedModule",1711,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__dictLN_string), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedModule2",1761,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__dictLN_string), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedStaveModule",2226,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__dictLN_string), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetStaveId",976,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__dictLN_string), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedCompTypeStave",2429,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedSystemType",2160,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__dictLN_ProcessPosition), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedSystemTypeStave",2675,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__dictLN_ProcessPosition), -1, 0, 1, 1, 2, 0, "i - - 0 - comp_type", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedSystemTypeB",2226,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__dictLN_ProcessPosition), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedSystemTypeStave",2675,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__dictLN_ProcessPosition), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedChip",1485,(G__InterfaceMethod) NULL, 104, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedChipB",1551,(G__InterfaceMethod) NULL, 104, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedHVType",1673,(G__InterfaceMethod) NULL, 104, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedHVTypeB",1739,(G__InterfaceMethod) NULL, 104, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSelectedHVTypeTh",1861,(G__InterfaceMethod) NULL, 104, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EnableModuleProcessPointRadioButtons",3700,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EnableModuleProcessPointRadioButtons2",3750,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EnableHVRadioButtons",1987,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EnableStaveProcessPointRadioButtons",3601,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EnableStaveModuleComparison",2763,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "i - - 0 - enable", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadStaveList",1311,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadModuleHistogramList",2352,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitializeGui",1335,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillModuleComboBox",1798,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "U 'TGComboBox' - 0 - box", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillStaveModuleComboBox",2313,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "U 'TGComboBox' - 0 - box", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResetMemberVariables",2036,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("MainGui", 682, G__dict_613_0_36, (int) ('i'), G__get_linked_tagnum(&G__dictLN_MainGui), -1, 0, 1, 1, 1, 0, "u 'MainGui' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~MainGui", 808, G__dict_613_0_37, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dict_613_0_38, (int) ('u'), G__get_linked_tagnum(&G__dictLN_MainGui), -1, 1, 1, 1, 1, 0, "u 'MainGui' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__dictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__dictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__dictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__dictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__dictLN_ProcessPosition = { "ProcessPosition" , 101 , -1 };
G__linked_taginfo G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlEScanDefcOallocatorlEScanDefgRsPgR = { "vector<ScanDef,allocator<ScanDef> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEScanDefcOallocatorlEScanDefgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ScanDef,allocator<ScanDef> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlEProcessPositioncOallocatorlEProcessPositiongRsPgR = { "vector<ProcessPosition,allocator<ProcessPosition> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEProcessPositioncOallocatorlEProcessPositiongRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ProcessPosition,allocator<ProcessPosition> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_HistoReader = { "HistoReader" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlETH2CmUcOallocatorlETH2CmUgRsPgR = { "vector<TH2C*,allocator<TH2C*> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETH2CmUcOallocatorlETH2CmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2C*,allocator<TH2C*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgR = { "vector<IVMeasurementPoint,allocator<IVMeasurementPoint> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<IVMeasurementPoint,allocator<IVMeasurementPoint> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgR = { "vector<HistoReader*,allocator<HistoReader*> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<HistoReader*,allocator<HistoReader*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR = { "vector<TGraph*,allocator<TGraph*> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGraph*,allocator<TGraph*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_MainGui = { "MainGui" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgR = { "vector<TGCheckButton*,allocator<TGCheckButton*> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGCheckButton*,allocator<TGCheckButton*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict() {
  G__dictLN_string.tagnum = -1 ;
  G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__dictLN_TGMainFrame.tagnum = -1 ;
  G__dictLN_TGRadioButton.tagnum = -1 ;
  G__dictLN_TGNumberEntry.tagnum = -1 ;
  G__dictLN_TGComboBox.tagnum = -1 ;
  G__dictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_TCanvas.tagnum = -1 ;
  G__dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__dictLN_ProcessPosition.tagnum = -1 ;
  G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_vectorlEScanDefcOallocatorlEScanDefgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEScanDefcOallocatorlEScanDefgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_vectorlEProcessPositioncOallocatorlEProcessPositiongRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEProcessPositioncOallocatorlEProcessPositiongRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_HistoReader.tagnum = -1 ;
  G__dictLN_vectorlETH2CmUcOallocatorlETH2CmUgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlETH2CmUcOallocatorlETH2CmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_vectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_vectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_MainGui.tagnum = -1 ;
  G__dictLN_vectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dictLN_string);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__dictLN_TGRadioButton);
   G__get_linked_tagnum_fwd(&G__dictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__dictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__dictLN_ProcessPosition);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEScanDefcOallocatorlEScanDefgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEScanDefcOallocatorlEScanDefgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEProcessPositioncOallocatorlEProcessPositiongRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEProcessPositioncOallocatorlEProcessPositiongRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_HistoReader);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlETH2CmUcOallocatorlETH2CmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlETH2CmUcOallocatorlETH2CmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEIVMeasurementPointcOallocatorlEIVMeasurementPointgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEHistoReadermUcOallocatorlEHistoReadermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictLN_MainGui),sizeof(MainGui),-1,256,(char*)NULL,G__setup_memvarMainGui,G__setup_memfuncMainGui);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlETGCheckButtonmUcOallocatorlETGCheckButtonmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupdict(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict()");
  G__set_cpp_environmentdict();
  G__cpp_setup_tagtabledict();

  G__cpp_setup_inheritancedict();

  G__cpp_setup_typetabledict();

  G__cpp_setup_memvardict();

  G__cpp_setup_memfuncdict();
  G__cpp_setup_globaldict();
  G__cpp_setup_funcdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict();
  return;
}
class G__cpp_setup_initdict {
  public:
    G__cpp_setup_initdict() { G__add_setup_func("dict",(G__incsetup)(&G__cpp_setupdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict() { G__remove_setup_func("dict"); }
};
G__cpp_setup_initdict G__cpp_setup_initializerdict;

